model_list:

  # OpenAI ChatGPT Models
  # - model_name: GPT-5
  #   litellm_params:
  #     model: openai/gpt-5
  #     api_key: os.environ/OPENAI_API_KEY

  # - model_name: GPT-5 mini
  #   litellm_params:
  #     model: openai/gpt-5-mini
  #     api_key: os.environ/OPENAI_API_KEY

  # - model_name: GPT-5 nano
  #   litellm_params:
  #     model: openai/gpt-5-nano
  #     api_key: os.environ/OPENAI_API_KEY

  # Google Gemini Models
  - model_name: Gemini 2.5 Pro
    litellm_params:
      model: gemini/gemini-2.5-pro
      api_key: os.environ/GEMINI_API_KEY

  - model_name: Gemini 2.5 Flash
    litellm_params:
      model: gemini/gemini-2.5-flash
      api_key: os.environ/GEMINI_API_KEY

  # Anthropic Claude Models
  - model_name: Claude Opus 4.1
    litellm_params:
      model: anthropic/claude-opus-4-1
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: Claude Sonnet 4.5
    litellm_params:
      model: anthropic/claude-sonnet-4-5
      api_key: os.environ/ANTHROPIC_API_KEY

  - model_name: Claude Haiku 4.5
    litellm_params:
      model: anthropic/claude-haiku-4-5
      api_key: os.environ/ANTHROPIC_API_KEY

  # PLaMo Models
  - model_name: PLaMo 2.1 Prime
    litellm_params:
      model: openai/plamo-2.1-prime
      api_key: os.environ/PLAMO_API_KEY
      api_base: https://api.platform.preferredai.jp/v1

  # OpenRouter Models
  - model_name: GPT-5
    litellm_params:
      model: openrouter/openai/gpt-5
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: GPT-5 mini
    litellm_params:
      model: openrouter/openai/gpt-5-mini
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: GPT-5 nano
    litellm_params:
      model: openrouter/openai/gpt-5-nano
      api_key: os.environ/OPENROUTER_API_KEY

  - model_name: z-ai-glm-4.5-air
    litellm_params:
      model: openrouter/z-ai/glm-4.5-air:free
      api_key: os.environ/OPENROUTER_API_KEY

  # Ollama Models
  - model_name: ollama
    litellm_params:
      model: ollama
      api_base: http://host.docker.internal:11434
